use galfus_realm_core::{
    RENDER_PASS_BLOOM, RENDER_PASS_COMPOSE, RENDER_PASS_CUSTOM_POST_FORWARD,
    RENDER_PASS_CUSTOM_PRE_FORWARD, RENDER_PASS_FORWARD, RENDER_PASS_LIGHT_CULL,
    RENDER_PASS_OUTLINE, RENDER_PASS_POST, RENDER_PASS_SHADOW, RENDER_PASS_SKYBOX,
    RENDER_PASS_SSAO, RENDER_PASS_SSAO_BLUR,
};

pub const SUPPORTED_RENDER_PASSES: &[&str] = &[
    RENDER_PASS_SHADOW,
    RENDER_PASS_LIGHT_CULL,
    RENDER_PASS_SKYBOX,
    RENDER_PASS_CUSTOM_PRE_FORWARD,
    RENDER_PASS_FORWARD,
    RENDER_PASS_CUSTOM_POST_FORWARD,
    RENDER_PASS_OUTLINE,
    RENDER_PASS_SSAO,
    RENDER_PASS_SSAO_BLUR,
    RENDER_PASS_BLOOM,
    RENDER_PASS_POST,
    RENDER_PASS_COMPOSE,
];

pub fn supports_render_pass(pass_id: &str) -> bool {
    SUPPORTED_RENDER_PASSES.contains(&pass_id)
}

pub fn graph_is_compatible<'a>(pass_ids: impl IntoIterator<Item = &'a str>) -> bool {
    pass_ids.into_iter().all(supports_render_pass)
}
