import type { EngineTransport } from '@vulfram/transport-types';
import type { CommandResponseEnvelope, EngineCmdEnvelope } from '../types/cmds';
import type { EngineEvent } from '../types/events';
import type { CmdRealmCreateArgs, RealmKind } from '../types/cmds/realm';
import type { Component, ComponentType, EngineRegistry, WorldEvent } from './ecs';
import type { IntentStore } from './intents/store';

type EngineStatus = 'uninitialized' | 'initialized' | 'disposed';

/**
 * Component storage indexed by Entity ID.
 */
export type ComponentStore = Map<ComponentType, Component>;

type ComponentIdCounters = {
  camera: number;
  light: number;
  model: number;
};

type ResourceIdCounters = {
  material: number;
  geometry: number;
  texture: number;
};

export type RoutingIndex = {
  dirty: boolean;
  byWindowId: Map<number, number[]>;
  byRealmId: Map<number, number[]>;
  byTargetId: Map<number, number[]>;
};

export type WorldState = {
  worldId: number;
  /**
   * Realm kind for this world.
   * `three-d` realms are used by World3D APIs and `two-d` realms by WorldUI APIs.
   */
  realmKind: RealmKind;
  primaryWindowId?: number;
  boundWindowIds: Set<number>;
  /**
   * Latest target-layer binding args keyed by targetId.
   * Used to keep realm->target binds coherent when cameras are created later.
   */
  targetLayerBindings: Map<
    number,
    {
      targetId: number;
      layout: import('../types/cmds/target').TargetLayerLayout;
      cameraId?: number;
      environmentId?: number;
    }
  >;
  /**
   * Window target ownership keyed by targetId.
   * Tracks which window a target is currently presenting into for routing purposes.
   */
  targetWindowBindings: Map<number, number>;
  coreRealmId?: number;
  realmCreateRetryCount: number;
  nextRealmCreateRetryAtMs: number;
  realmCreateArgs: CmdRealmCreateArgs;
  coreSurfaceId?: number;
  corePresentId?: number;
  /**
   * Constraint-solved world matrices keyed by entity id.
   */
  resolvedEntityTransforms: Map<number, Float32Array>;
  /**
   * Entities explicitly marked as dirty for constraint recomputation.
   */
  constraintDirtyEntities: Set<number>;
  /**
   * Scratch cache for per-tick constraint solve graph resolution.
   */
  constraintScratchResolved: Map<number, Float32Array>;
  /**
   * Scratch set used while resolving hierarchy recursion (cycle detection).
   */
  constraintScratchVisiting: Set<number>;
  /**
   * Entities with resolved matrix changes in the current tick.
   */
  constraintChangedEntities: Set<number>;
  /**
   * Parent -> children relationship index for hierarchy propagation.
   */
  constraintChildrenByParent: Map<number, Set<number>>;
  /**
   * Child -> parent relationship index for fast reparent operations.
   */
  constraintParentByChild: Map<number, number>;
  /**
   * Reusable scratch arrays used when syncing matrices to core.
   */
  sceneSyncMatrixScratch: Map<number, number[]>;
  entities: Set<number>;
  /**
   * Components stored by entityId -> componentType -> ComponentData
   */
  components: Map<number, ComponentStore>;
  nextCoreId: number;
  systems: string[];
  /**
   * Indexed intent store to query/consume by type with stable insertion order.
   */
  intentStore: IntentStore;
  /**
   * Internal world events for system-to-system communication.
   */
  internalEvents: WorldEvent[];
  /**
   * Pending commands generated by this world in the current frame.
   * Will be moved to the engine's global batch during the tick.
   */
  pendingCommands: EngineCmdEnvelope[];
  pendingCommandsHead: number;
  /**
   * Events routed to this world in the current frame.
   */
  inboundEvents: EngineEvent[];
  /**
   * Responses routed to this world in the current frame.
   */
  inboundResponses: CommandResponseEnvelope[];
};

export type EngineState = {
  status: EngineStatus;
  transport: EngineTransport | null;
  worlds: Map<number, WorldState>;
  nextWorldId: number;
  nextWindowId: number;
  nextEntityId: number;
  nextCommandId: number;
  /**
   * Global ID allocator for core-global resources/objects.
   * Use for IDs that are not realm-scoped (material/geometry/texture/target/...).
   */
  nextGlobalId: number;
  /**
   * Global command batch for the current frame.
   */
  commandBatch: EngineCmdEnvelope[];
  /**
   * Tracks reserved window IDs to avoid logical ID collisions for host windows.
   */
  usedWindowIds: Set<number>;
  /**
   * Pending global commands not scoped to any specific world.
   */
  globalPendingCommands: EngineCmdEnvelope[];
  globalPendingCommandsHead: number;
  /**
   * Window IDs confirmed by core `window-create` responses.
   */
  confirmedWindowIds: Set<number>;
  /**
   * Maps pending window-create command ids to requested window ids.
   */
  pendingWindowCreateByCommandId: Map<number, number>;
  /**
   * Maps pending window-close command ids to target window ids.
   */
  pendingWindowCloseByCommandId: Map<number, number>;
  /**
   * Maps command IDs to the world ID that created them.
   * This is used to route responses back to the correct world.
   */
  commandTracker: Map<number, number>;
  /**
   * Tracks global commands (not world-scoped) so their responses are not lost.
   */
  globalCommandTracker: Set<number>;
  /**
   * Buffered responses for global commands.
   */
  globalInboundResponses: CommandResponseEnvelope[];
  /**
   * Cached world routing index for event fanout.
   */
  routingIndex: RoutingIndex;
  /**
   * Registry for custom components and systems.
   */
  registry: EngineRegistry;
  /**
   * Engine clock information.
   */
  clock: {
    lastTime: number;
    lastDelta: number;
    frameCount: number;
  };
  /**
   * Internal flags for protection and debugging.
   */
  flags: {
    isExecutingSystems: boolean;
    debugEnabled: boolean;
  };
};

export const REQUIRED_SYSTEMS = [
  'InputMirrorSystem',
  'CommandIntentSystem',
  'UiBridgeSystem',
  'ResourceUploadSystem',
  'ConstraintSolveSystem',
  'SceneSyncSystem',
  'ResponseDecodeSystem',
  'WorldLifecycleSystem',
  'DiagnosticsSystem'
];

export const engineState: EngineState = {
  status: 'uninitialized',
  transport: null,
  worlds: new Map(),
  nextWorldId: 1,
  nextWindowId: 1,
  nextEntityId: 1,
  nextCommandId: 1,
  nextGlobalId: 100,
  commandBatch: [],
  usedWindowIds: new Set(),
  globalPendingCommands: [],
  globalPendingCommandsHead: 0,
  confirmedWindowIds: new Set(),
  pendingWindowCreateByCommandId: new Map(),
  pendingWindowCloseByCommandId: new Map(),
  commandTracker: new Map(),
  globalCommandTracker: new Set(),
  globalInboundResponses: [],
  routingIndex: {
    dirty: true,
    byWindowId: new Map(),
    byRealmId: new Map(),
    byTargetId: new Map()
  },
  registry: {
    components: new Map(),
    systems: {
      input: [],
      update: [],
      preRender: [],
      postRender: []
    }
  },
  clock: {
    lastTime: 0,
    lastDelta: 0,
    frameCount: 0
  },
  flags: {
    isExecutingSystems: false,
    debugEnabled: false
  }
};
