use crate::core::resources::PostProcessConfig;

pub fn build_demo_004_post_config() -> PostProcessConfig {
    PostProcessConfig {
        filter_enabled: false,
        filter_exposure: 1.0,
        filter_gamma: 1.0,
        filter_saturation: 1.0,
        filter_contrast: 1.0,
        filter_vignette: 0.0,
        filter_grain: 0.0,
        filter_chromatic_aberration: 0.0,
        filter_blur: 0.0,
        filter_sharpen: 0.0,
        filter_tonemap_mode: 1,
        outline_enabled: true,
        outline_strength: 0.6,
        outline_threshold: 0.0,
        outline_width: 2.0,
        outline_quality: 1.0,
        filter_posterize_steps: 1.0,
        cell_shading: false,
        ssao_enabled: true,
        ssao_strength: 0.75,
        ssao_radius: 0.9,
        ssao_bias: 0.02,
        ssao_power: 1.3,
        ssao_blur_radius: 2.0,
        ssao_blur_depth_threshold: 0.02,
        bloom_enabled: true,
        bloom_threshold: 1.0,
        bloom_knee: 0.8,
        bloom_intensity: 1.0,
        bloom_scatter: 1.0,
    }
}
