use std::collections::HashMap;
use vulfram_realm_core::{
    RENDER_PASS_BLOOM, RENDER_PASS_COMPOSE, RENDER_PASS_FORWARD, RENDER_PASS_LIGHT_CULL,
    RENDER_PASS_OUTLINE, RENDER_PASS_POST, RENDER_PASS_SHADOW, RENDER_PASS_SKYBOX,
    RENDER_PASS_SSAO, RENDER_PASS_SSAO_BLUR, RENDER_PASS_UI,
};

use crate::{
    LogicalId, RenderGraphDesc, RenderGraphEdge, RenderGraphEdgeReason, RenderGraphLifetime,
    RenderGraphNode, RenderGraphResource, RenderGraphResourceKind,
};

pub fn ui_fallback_graph() -> RenderGraphDesc {
    RenderGraphDesc {
        graph_id: LogicalId::Str("ui_fallback".into()),
        nodes: vec![RenderGraphNode {
            node_id: LogicalId::Str("ui_pass".into()),
            pass_id: RENDER_PASS_UI.into(),
            inputs: Vec::new(),
            outputs: vec![LogicalId::Str("swapchain".into())],
            require: Vec::new(),
            priority: 100,
            enabled: true,
            params: HashMap::new(),
            shader: None,
        }],
        edges: Vec::new(),
        resources: vec![RenderGraphResource {
            res_id: LogicalId::Str("swapchain".into()),
            kind: RenderGraphResourceKind::Attachment,
            lifetime: RenderGraphLifetime::Frame,
            alias_group: None,
        }],
        fallback: true,
    }
}

pub fn fallback_graph() -> RenderGraphDesc {
    RenderGraphDesc {
        graph_id: LogicalId::Str("fallback".into()),
        nodes: vec![
            RenderGraphNode {
                node_id: LogicalId::Str("shadow_pass".into()),
                pass_id: RENDER_PASS_SHADOW.into(),
                inputs: Vec::new(),
                outputs: vec![LogicalId::Str("shadow_atlas".into())],
                require: Vec::new(),
                priority: 10,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("light_cull_pass".into()),
                pass_id: RENDER_PASS_LIGHT_CULL.into(),
                inputs: Vec::new(),
                outputs: Vec::new(),
                require: Vec::new(),
                priority: 20,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("skybox_pass".into()),
                pass_id: RENDER_PASS_SKYBOX.into(),
                inputs: Vec::new(),
                outputs: vec![LogicalId::Str("hdr_color".into())],
                require: Vec::new(),
                priority: 30,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("forward_pass".into()),
                pass_id: RENDER_PASS_FORWARD.into(),
                inputs: vec![
                    LogicalId::Str("shadow_atlas".into()),
                    LogicalId::Str("hdr_color".into()),
                ],
                outputs: vec![
                    LogicalId::Str("hdr_color".into()),
                    LogicalId::Str("depth".into()),
                ],
                require: Vec::new(),
                priority: 40,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("outline_pass".into()),
                pass_id: RENDER_PASS_OUTLINE.into(),
                inputs: vec![LogicalId::Str("depth".into())],
                outputs: vec![LogicalId::Str("outline_color".into())],
                require: Vec::new(),
                priority: 50,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("ssao_pass".into()),
                pass_id: RENDER_PASS_SSAO.into(),
                inputs: vec![LogicalId::Str("depth".into())],
                outputs: vec![LogicalId::Str("ssao_raw".into())],
                require: Vec::new(),
                priority: 60,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("ssao_blur_pass".into()),
                pass_id: RENDER_PASS_SSAO_BLUR.into(),
                inputs: vec![
                    LogicalId::Str("ssao_raw".into()),
                    LogicalId::Str("depth".into()),
                ],
                outputs: vec![LogicalId::Str("ssao_blur".into())],
                require: Vec::new(),
                priority: 70,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("bloom_pass".into()),
                pass_id: RENDER_PASS_BLOOM.into(),
                inputs: vec![LogicalId::Str("hdr_color".into())],
                outputs: vec![LogicalId::Str("bloom_color".into())],
                require: Vec::new(),
                priority: 80,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("post_pass".into()),
                pass_id: RENDER_PASS_POST.into(),
                inputs: vec![
                    LogicalId::Str("hdr_color".into()),
                    LogicalId::Str("outline_color".into()),
                    LogicalId::Str("ssao_blur".into()),
                    LogicalId::Str("bloom_color".into()),
                ],
                outputs: vec![LogicalId::Str("post_color".into())],
                require: Vec::new(),
                priority: 90,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("compose_pass".into()),
                pass_id: RENDER_PASS_COMPOSE.into(),
                inputs: vec![LogicalId::Str("post_color".into())],
                outputs: vec![LogicalId::Str("swapchain".into())],
                require: Vec::new(),
                priority: 100,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
            RenderGraphNode {
                node_id: LogicalId::Str("ui_pass".into()),
                pass_id: RENDER_PASS_UI.into(),
                inputs: vec![LogicalId::Str("swapchain".into())],
                outputs: vec![LogicalId::Str("swapchain".into())],
                require: Vec::new(),
                priority: 110,
                enabled: true,
                params: HashMap::new(),
                shader: None,
            },
        ],
        edges: vec![
            RenderGraphEdge {
                from_node_id: LogicalId::Str("shadow_pass".into()),
                to_node_id: LogicalId::Str("forward_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("light_cull_pass".into()),
                to_node_id: LogicalId::Str("skybox_pass".into()),
                reason: None,
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("skybox_pass".into()),
                to_node_id: LogicalId::Str("forward_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("forward_pass".into()),
                to_node_id: LogicalId::Str("outline_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("forward_pass".into()),
                to_node_id: LogicalId::Str("ssao_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("ssao_pass".into()),
                to_node_id: LogicalId::Str("ssao_blur_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("ssao_blur_pass".into()),
                to_node_id: LogicalId::Str("post_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("forward_pass".into()),
                to_node_id: LogicalId::Str("bloom_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("bloom_pass".into()),
                to_node_id: LogicalId::Str("post_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("outline_pass".into()),
                to_node_id: LogicalId::Str("post_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("post_pass".into()),
                to_node_id: LogicalId::Str("compose_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
            RenderGraphEdge {
                from_node_id: LogicalId::Str("compose_pass".into()),
                to_node_id: LogicalId::Str("ui_pass".into()),
                reason: Some(RenderGraphEdgeReason::ReadAfterWrite),
            },
        ],
        resources: vec![
            RenderGraphResource {
                res_id: LogicalId::Str("shadow_atlas".into()),
                kind: RenderGraphResourceKind::Texture,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("hdr_color".into()),
                kind: RenderGraphResourceKind::Attachment,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("depth".into()),
                kind: RenderGraphResourceKind::Attachment,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("outline_color".into()),
                kind: RenderGraphResourceKind::Texture,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("ssao_raw".into()),
                kind: RenderGraphResourceKind::Texture,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("ssao_blur".into()),
                kind: RenderGraphResourceKind::Texture,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("bloom_color".into()),
                kind: RenderGraphResourceKind::Texture,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("post_color".into()),
                kind: RenderGraphResourceKind::Attachment,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
            RenderGraphResource {
                res_id: LogicalId::Str("swapchain".into()),
                kind: RenderGraphResourceKind::Attachment,
                lifetime: RenderGraphLifetime::Frame,
                alias_group: None,
            },
        ],
        fallback: true,
    }
}
