use crate::{
    FallbackTextures, Layouts, PipelineLayouts, ResourceLibrary, SamplerSet, ShaderModules,
};

pub fn build_resource_library(
    layouts: Layouts,
    pipeline_layouts: PipelineLayouts,
    shaders: ShaderModules,
    samplers: SamplerSet,
    fallbacks: FallbackTextures,
) -> ResourceLibrary {
    ResourceLibrary {
        layout_shared: layouts.shared,
        layout_object: layouts.object,
        layout_object_standard: layouts.object_standard,
        layout_object_pbr: layouts.object_pbr,
        layout_target: layouts.target,
        layout_light_cull: layouts.light_cull,
        layout_ssao: layouts.ssao,
        layout_ssao_blur: layouts.ssao_blur,
        layout_ssao_msaa: layouts.ssao_msaa,
        layout_ssao_blur_msaa: layouts.ssao_blur_msaa,
        layout_bloom: layouts.bloom,
        layout_skybox: layouts.skybox,
        forward_standard_pipeline_layout: pipeline_layouts.forward_standard,
        forward_pbr_pipeline_layout: pipeline_layouts.forward_pbr,
        shadow_pipeline_layout: pipeline_layouts.shadow,
        outline_pipeline_layout: pipeline_layouts.outline,
        ssao_pipeline_layout: pipeline_layouts.ssao,
        ssao_blur_pipeline_layout: pipeline_layouts.ssao_blur,
        ssao_msaa_pipeline_layout: pipeline_layouts.ssao_msaa,
        ssao_blur_msaa_pipeline_layout: pipeline_layouts.ssao_blur_msaa,
        bloom_pipeline_layout: pipeline_layouts.bloom,
        skybox_pipeline_layout: pipeline_layouts.skybox,
        post_shader: shaders.post,
        compose_shader: shaders.compose,
        outline_shader: shaders.outline,
        ssao_shader: shaders.ssao,
        ssao_blur_shader: shaders.ssao_blur,
        ssao_msaa_shader: shaders.ssao_msaa,
        ssao_blur_msaa_shader: shaders.ssao_blur_msaa,
        bloom_shader: shaders.bloom,
        skybox_shader: shaders.skybox,
        light_cull_shader: shaders.light_cull,
        shadow_shader: shaders.shadow,
        gizmo_shader: shaders.gizmo,
        light_cull_pipeline_layout: pipeline_layouts.light_cull,
        gizmo_pipeline_layout: pipeline_layouts.gizmo,
        samplers,
        _fallback_texture: fallbacks.texture,
        fallback_view: fallbacks.view,
        _fallback_forward_atlas_texture: fallbacks.atlas_texture,
        fallback_forward_atlas_view: fallbacks.atlas_view,
        _fallback_shadow_texture: fallbacks.shadow_texture,
        fallback_shadow_view: fallbacks.shadow_view,
    }
}
