#[cfg(not(target_arch = "wasm32"))]
use vulfram_input::{KEY_UNIDENTIFIED, TouchPhase};
#[cfg(not(target_arch = "wasm32"))]
use winit::event::{MouseButton, TouchPhase as WinitTouchPhase};
#[cfg(not(target_arch = "wasm32"))]
use winit::keyboard::{KeyCode, KeyLocation, PhysicalKey};

#[cfg(not(target_arch = "wasm32"))]
pub fn map_winit_touch_phase(phase: WinitTouchPhase) -> TouchPhase {
    match phase {
        WinitTouchPhase::Started => TouchPhase::Started,
        WinitTouchPhase::Moved => TouchPhase::Moved,
        WinitTouchPhase::Ended => TouchPhase::Ended,
        WinitTouchPhase::Cancelled => TouchPhase::Cancelled,
    }
}

#[cfg(not(target_arch = "wasm32"))]
pub fn map_winit_mouse_button(button: MouseButton) -> u32 {
    match button {
        MouseButton::Left => 0,
        MouseButton::Right => 1,
        MouseButton::Middle => 2,
        MouseButton::Back => 3,
        MouseButton::Forward => 4,
        MouseButton::Other(id) => id as u32,
    }
}

#[cfg(not(target_arch = "wasm32"))]
pub fn map_winit_key_location(location: KeyLocation) -> u32 {
    match location {
        KeyLocation::Standard => 0,
        KeyLocation::Left => 1,
        KeyLocation::Right => 2,
        KeyLocation::Numpad => 3,
    }
}

#[cfg(not(target_arch = "wasm32"))]
pub fn map_winit_physical_key_code(physical_key: &PhysicalKey) -> u32 {
    match physical_key {
        PhysicalKey::Code(code) => map_winit_key_code(*code),
        PhysicalKey::Unidentified(_) => KEY_UNIDENTIFIED,
    }
}

#[cfg(not(target_arch = "wasm32"))]
pub fn map_winit_key_code(code: KeyCode) -> u32 {
    use KeyCode as WKeyCode;

    match code {
        WKeyCode::Backquote => 0,
        WKeyCode::Backslash => 1,
        WKeyCode::BracketLeft => 2,
        WKeyCode::BracketRight => 3,
        WKeyCode::Comma => 4,
        WKeyCode::Digit0 => 5,
        WKeyCode::Digit1 => 6,
        WKeyCode::Digit2 => 7,
        WKeyCode::Digit3 => 8,
        WKeyCode::Digit4 => 9,
        WKeyCode::Digit5 => 10,
        WKeyCode::Digit6 => 11,
        WKeyCode::Digit7 => 12,
        WKeyCode::Digit8 => 13,
        WKeyCode::Digit9 => 14,
        WKeyCode::Equal => 15,
        WKeyCode::IntlBackslash => 16,
        WKeyCode::IntlRo => 17,
        WKeyCode::IntlYen => 18,
        WKeyCode::KeyA => 19,
        WKeyCode::KeyB => 20,
        WKeyCode::KeyC => 21,
        WKeyCode::KeyD => 22,
        WKeyCode::KeyE => 23,
        WKeyCode::KeyF => 24,
        WKeyCode::KeyG => 25,
        WKeyCode::KeyH => 26,
        WKeyCode::KeyI => 27,
        WKeyCode::KeyJ => 28,
        WKeyCode::KeyK => 29,
        WKeyCode::KeyL => 30,
        WKeyCode::KeyM => 31,
        WKeyCode::KeyN => 32,
        WKeyCode::KeyO => 33,
        WKeyCode::KeyP => 34,
        WKeyCode::KeyQ => 35,
        WKeyCode::KeyR => 36,
        WKeyCode::KeyS => 37,
        WKeyCode::KeyT => 38,
        WKeyCode::KeyU => 39,
        WKeyCode::KeyV => 40,
        WKeyCode::KeyW => 41,
        WKeyCode::KeyX => 42,
        WKeyCode::KeyY => 43,
        WKeyCode::KeyZ => 44,
        WKeyCode::Minus => 45,
        WKeyCode::Period => 46,
        WKeyCode::Quote => 47,
        WKeyCode::Semicolon => 48,
        WKeyCode::Slash => 49,
        WKeyCode::AltLeft => 50,
        WKeyCode::AltRight => 51,
        WKeyCode::Backspace => 52,
        WKeyCode::CapsLock => 53,
        WKeyCode::ContextMenu => 54,
        WKeyCode::ControlLeft => 55,
        WKeyCode::ControlRight => 56,
        WKeyCode::Enter => 57,
        WKeyCode::SuperLeft => 58,
        WKeyCode::SuperRight => 59,
        WKeyCode::ShiftLeft => 60,
        WKeyCode::ShiftRight => 61,
        WKeyCode::Space => 62,
        WKeyCode::Tab => 63,
        WKeyCode::Delete => 64,
        WKeyCode::End => 65,
        WKeyCode::Help => 66,
        WKeyCode::Home => 67,
        WKeyCode::Insert => 68,
        WKeyCode::PageDown => 69,
        WKeyCode::PageUp => 70,
        WKeyCode::ArrowDown => 71,
        WKeyCode::ArrowLeft => 72,
        WKeyCode::ArrowRight => 73,
        WKeyCode::ArrowUp => 74,
        WKeyCode::NumLock => 75,
        WKeyCode::Numpad0 => 76,
        WKeyCode::Numpad1 => 77,
        WKeyCode::Numpad2 => 78,
        WKeyCode::Numpad3 => 79,
        WKeyCode::Numpad4 => 80,
        WKeyCode::Numpad5 => 81,
        WKeyCode::Numpad6 => 82,
        WKeyCode::Numpad7 => 83,
        WKeyCode::Numpad8 => 84,
        WKeyCode::Numpad9 => 85,
        WKeyCode::NumpadAdd => 86,
        WKeyCode::NumpadBackspace => 87,
        WKeyCode::NumpadClear => 88,
        WKeyCode::NumpadClearEntry => 89,
        WKeyCode::NumpadComma => 90,
        WKeyCode::NumpadDecimal => 91,
        WKeyCode::NumpadDivide => 92,
        WKeyCode::NumpadEnter => 93,
        WKeyCode::NumpadEqual => 94,
        WKeyCode::NumpadHash => 95,
        WKeyCode::NumpadMemoryAdd => 96,
        WKeyCode::NumpadMemoryClear => 97,
        WKeyCode::NumpadMemoryRecall => 98,
        WKeyCode::NumpadMemoryStore => 99,
        WKeyCode::NumpadMemorySubtract => 100,
        WKeyCode::NumpadMultiply => 101,
        WKeyCode::NumpadParenLeft => 102,
        WKeyCode::NumpadParenRight => 103,
        WKeyCode::NumpadStar => 104,
        WKeyCode::NumpadSubtract => 105,
        WKeyCode::Escape => 106,
        WKeyCode::F1 => 107,
        WKeyCode::F2 => 108,
        WKeyCode::F3 => 109,
        WKeyCode::F4 => 110,
        WKeyCode::F5 => 111,
        WKeyCode::F6 => 112,
        WKeyCode::F7 => 113,
        WKeyCode::F8 => 114,
        WKeyCode::F9 => 115,
        WKeyCode::F10 => 116,
        WKeyCode::F11 => 117,
        WKeyCode::F12 => 118,
        WKeyCode::F13 => 119,
        WKeyCode::F14 => 120,
        WKeyCode::F15 => 121,
        WKeyCode::F16 => 122,
        WKeyCode::F17 => 123,
        WKeyCode::F18 => 124,
        WKeyCode::F19 => 125,
        WKeyCode::F20 => 126,
        WKeyCode::F21 => 127,
        WKeyCode::F22 => 128,
        WKeyCode::F23 => 129,
        WKeyCode::F24 => 130,
        WKeyCode::ScrollLock => 131,
        WKeyCode::AudioVolumeDown => 132,
        WKeyCode::AudioVolumeMute => 133,
        WKeyCode::AudioVolumeUp => 134,
        WKeyCode::MediaPlayPause => 135,
        WKeyCode::MediaStop => 136,
        WKeyCode::MediaTrackNext => 137,
        WKeyCode::MediaTrackPrevious => 138,
        WKeyCode::BrowserBack => 139,
        WKeyCode::BrowserFavorites => 140,
        WKeyCode::BrowserForward => 141,
        WKeyCode::BrowserHome => 142,
        WKeyCode::BrowserRefresh => 143,
        WKeyCode::BrowserSearch => 144,
        WKeyCode::BrowserStop => 145,
        WKeyCode::PrintScreen => 146,
        WKeyCode::Pause => 147,
        _ => KEY_UNIDENTIFIED,
    }
}
