export {
  applyGamepadEvent,
  applyKeyboardEvent,
  applyPointerEvent,
  ensureInputMirrorState,
  INPUT_FRAME_RESET_POLICY,
  type CanonicalGamepadState,
  type CanonicalInputState,
  type CanonicalSystemEventState,
  type CanonicalUiEventState,
  type CanonicalWindowState,
  resetInputMirrorFrame,
  type InputMirrorStateStore,
  type InputFrameResetPolicy
} from './core';
export {
  getConnectedGamepads,
  getGamepadAxis,
  getGamepadEvents,
  getImeCommitText,
  getImeCursorRange,
  getImePreeditText,
  getLastSystemError,
  getPointerDelta,
  getPointerPosition,
  getPointerWindowSize,
  getScrollDelta,
  getSystemEvents,
  getUiEvents,
  getWindowLifecycleState,
  getWindowPosition,
  getWindowPointerCaptureState,
  getWindowScaleFactor,
  getWindowSize,
  isImeEnabled,
  isGamepadButtonPressed,
  isKeyPressed,
  isKeyJustPressed,
  isKeyJustReleased,
  isPointerButtonJustPressed,
  isPointerButtonPressed,
  isWindowFocused,
  isWindowCloseRequested,
  wasWindowResized
} from './queries';
